# elirazo96
# Admin Dashboard Access by Unauthorized User
# Query Information
# MITRE ATT&CK Tactic: Credential Access (T1078)
# Description: Identifies any accesses to the admin dashboard by users not authorized to do so, helping detect potential account compromises.

ACME_INTERNAL_System
| where LogLevel == "INFO"
| where Event ID == "Access Granted"
| where User !in (adminusers)
| where Resource contains "admin-dashboard"
| project Timestamp, LogLevel, SourceIP, EventDescription, User, Resource

# Admin Dashboard Access by User From Different IP in Short Period
# Query Information
# MITRE ATT&CK Tactic: Credential Access (T1078)
# Description: where a user accesses the admin dashboard from multiple IP addresses within a short timeframe,  its suggesting possible unauthorized use of credentials.

ACME_INTERNAL_System
| where LogLevel == "INFO"
| where Event ID == "Access Granted"
| summarize dcount(IP Address),make_set(IP Address) by User, bin(TimeGeneratedd,5h)
| where dcount _IP Address >= 2
| project Timestamp, LogLevel, SourceIP, EventDescription, User, Resource

# Admin Dashboard Access by User From Unauthorized IP
# Query Information
# MITRE ATT&CK Tactic: Credential Access (T1078)
# Description: where accesses to the admin dashboard from IP addresses not considered trusted, indicating potential attempts by adversaries using stolen credentials or unauthorized access attempts.

ACME_INTERNAL_System
| where LogLevel == "INFO"
| where Event ID == "Access Granted"
| where IP Address !in (trusted_ip)
| project Timestamp, LogLevel, SourceIP, EventDescription, User, Resource
